### ISSUE TITLE
Chrome 100 renders as 10

### ISSUE THREAD

**Issue by lukewarlow** [ericlaw1979/ShowChromeVersion#12]
After enabling the `#force-major-version-to-100` flag in Canary 96, I've noticed that this extension renders the version as 10 not 100.

![image](https://user-images.githubusercontent.com/32498324/134221324-1afdf037-b44c-421b-a3bd-74233cf5ad65.png)

Full User Agent String: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4649.0 Safari/537.36`

User Agent Data Brands:
![image](https://user-images.githubusercontent.com/32498324/134221614-008625d8-96dd-44bc-8a9f-83e26957a4c9.png)

**Comment by ericlaw1979** [comment]
thanks. This is indeed one of my examples in https://textslashplain.com/2021/10/01/practical-time-machines/
